#server:
#  port: 9090
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/Kyc_Information
#    username: postgres
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.PostgresSQLDialect
#      format-sql: true


server:
 port: 9090

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/Kyc_Information
  username: postgres
  password: varsha


